FROM php:8.1-apache
RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    vim \
    unzip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install pdo pdo_mysql
LABEL Name=noteapp Version=0.0.1
WORKDIR /var/www/html
COPY . /var/www/html
EXPOSE 80

