version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8000:80
    container_name: noteapp
    restart: always
    volumes:
      - ./:/var/www/html
  db:
    container_name: notedb
    image: mysql:8
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8001
