version: '3.8'

services:
  crud:
    image: crud
    container_name: crud
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./:/var/www/html




